# Generated by Django 4.2.1 on 2023-05-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('codigo', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=256)),
                ('fecha_publicacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('dni', models.CharField(max_length=32)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Escritor',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
