# Generated by Django 4.2.1 on 2023-05-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0002_articulo_lector_rename_estudiante_escritor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
