# Generated by Django 4.2.1 on 2023-05-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0003_delete_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='telefono',
        ),
    ]
