# Generated by Django 4.2.1 on 2023-05-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0004_remove_lector_dni_remove_lector_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escritor',
            options={'verbose_name_plural': 'Escritores'},
        ),
    ]
